admins:
- dog
channels:
  '#dogtest':
     key: ""
host: host.net 
ident: dogtester
nick: dogtester
altnick: evildogtester
owner: dog
port: 6667
realname: dogtester
cmds:
  chan:
    weather:
      cmd: /opt/dogbot/bin/weather.py -z 
      help: 'weather by zipcode (Ex. weather 90210)'
      acl: False
  priv:
    uptime:
      cmd: /usr/bin/uptime
      help: 'Execute uptime on server (admins only)'
      acl: True
